my_dict = {'Александр': 1996, 'Никита':1998,'Елена':2001, 'Анна':2003}
print('Dict:',my_dict)
print('Existing value:',my_dict['Александр'])
print('Not existing value:',my_dict.get('Семен','Нет данных'))
my_dict.update({'Виктория':2000,'Георгий': 1995})
Deleted_value=my_dict.pop('Анна')
print('Deleted value:',Deleted_value)
print('Modified dictionary:',my_dict,'\n ')
my_set = (1,1,12,'выхухоль',1.12,True,(1,2,3),(1,2,3))
my_set = set(my_set)
print('Set:',my_set)
my_set.add(3)
my_set.add("фунфурик")
my_set.discard((1,2,3))
print('Modified set: :',my_set)